// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'secret',
    appId: '1:654070904048:web:257e9f2bbac01f8b18be35',
    messagingSenderId: '654070904048',
    projectId: 'loginsignup-e2572',
    authDomain: 'loginsignup-e2572.firebaseapp.com',
    storageBucket: 'loginsignup-e2572.firebasestorage.app',
    measurementId: 'G-S64PMB11XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'secret',
    appId: '1:654070904048:android:35ebbbf27b77ad7e18be35',
    messagingSenderId: '654070904048',
    projectId: 'loginsignup-e2572',
    storageBucket: 'loginsignup-e2572.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'secret',
    appId: '1:654070904048:web:9529795d963075b218be35',
    messagingSenderId: '654070904048',
    projectId: 'loginsignup-e2572',
    authDomain: 'loginsignup-e2572.firebaseapp.com',
    storageBucket: 'loginsignup-e2572.firebasestorage.app',
    measurementId: 'G-1VKBCCQLES',
  );

}